#!/usr/bin/env python
# coding: utf-8

# In[ ]:


##If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
##Find the sum of all the multiples of 3 or 5 below 1000.


# In[1]:


sum(x for x in range(1000) if x%3==0 or x%5==0)


# In[ ]:


##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


# In[5]:


x=1
y=2
fibo=[x,y]
while y < 4000000:
    x, y=y, x+y
    fibo.append(y)
sum(x for x in fibo if x%2==0)


# In[ ]:


##The prime factors of 13195 are 5, 7, 13 and 29.
##What is the largest prime factor of the number 600851475143 ?


# In[6]:


def euler(p):
    i=2
    o=p
    for x in range(2,p):
        if p-x==0:
            break
        while p%x==0:
            p = p/x
    return(x)
print(euler(600851475143))


# In[ ]:


##A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
##Find the largest palindrome made from the product of two 3-digit numbers.


# In[7]:


def Pali(x):
    x = str(x)
    if x == x[::-1]:
        y=True
    else:
        y=False
    return y

l=[]
for a in range(100,1000):
    for b in range(100,1000):
        if Pali(a*b)==True:
            l.append(a*b)
max(l)


# In[ ]:




